[package]
name = "imag"
version = "0.1.0"
authors = ["rdh"]
edition = "2018"

[dependencies]
zopfli = "0.8.0"
oxipng = "9.0.0"
jni = "0.21.1"

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"

[lib]
crate_type = ["cdylib"]