name: build
on: [ pull_request, push ]

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip]')"
    strategy:
      matrix:
        java: [ 19.0.2 ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: gradle

      - name: setup rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: give gradle execution permissions
        run: chmod +x ./gradlew

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@9aa31f26bc8e536d1faf4b332bb8365350743a18

      - name: building
        run: ./gradlew assemble

      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: imag-artifacts
          path: build/libs/*.jar